#!/bin/bash

set -eo pipefail

cd /tmp

wget -q -O otp.tar.gz https://repo.hex.pm/builds/otp/ubuntu-14.04/OTP-${1}.tar.gz
mkdir -p .otp
tar zxf otp.tar.gz -C .otp --strip-components=1
rm otp.tar.gz
.otp/Install -minimal $(pwd)/.otp
echo "::add-path::$(pwd)/.otp/bin"
